### ISSUE TITLE
ImportError: No module named 'azure.common'

### ISSUE THREAD

**Issue by forhonourlx** [cxxgtxy/deeprl-baselines#1]
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\lib\site-packages\baselines-0.1.4-py3.5.egg\baselines\rainbow\experiments\atari\rainbow.py", line 27, in <module>
  File "C:\Program Files\Python35\lib\site-packages\baselines-0.1.4-py3.5.egg\baselines\common\azure_utils.py", line 5, in <module>
ImportError: No module named 'azure.common'

**Comment by cxxgtxy** [comment]
You need to install azure first. 
Take pip for example:
`pip install azure`

**Comment by forhonourlx** [comment]
It is quite strange that if only 'pip install azure', the import error would occur.
But 'pip install azure-common azure-storage' works well.
The env Python3.5 on Windows10.
Thank you for your help.

**Comment by cxxgtxy** [comment]
Welcome
